services:
  api-rag-assistant:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rag-assistant-api-image
    container_name: api-rag-assistant
    restart: always
    env_file:
      - .env
    depends_on:
      - db-rag-assistant
      - redis-rag-assistant
    networks:
      - rag-assistant-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["./wait-for-it.sh", "db-rag-assistant:5432", "--", "./start_api.sh"]
    volumes:
      - ./:/app

  webserver-rag-assistant:
    image: nginx:latest
    container_name: webserver-rag-assistant
    restart: always
    env_file:
      - .env
    ports:
      - "${WEBSERVER_HOST_PORT:-8001}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-rag-assistant
    networks:
      - rag-assistant-network

  db-rag-assistant:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    image: postgres-pgvector:15
    container_name: db-rag-assistant
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tutor_db
      POSTGRES_USER: tutor_user
      POSTGRES_PASSWORD: tutor_pass
    networks:
      - rag-assistant-network

  redis-rag-assistant:
    image: "redis:latest"
    container_name: redis-rag-assistant
    restart: always
    networks:
      - rag-assistant-network

volumes:
  postgres_data:

networks:
  rag-assistant-network:
    driver: bridge
