[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tutor-assistant"
version = "0.1.0"
description = "Production-ready Django/DRF API with JWT, user profile, and RAG assistant (LangChain, FAISS, LLM)"
authors = [
    { name="Emmanuel Molero" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
exclude = .git,__pycache__,docs,build,dist

[tool.mypy]
ignore_missing_imports = true
